//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PingMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Was the ping enabled for the primary target
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Was the ping enabled for the primary target")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool primaryTargetEnabled {
            get {
                return ((bool)(this["primaryTargetEnabled"]));
            }
            set {
                this["primaryTargetEnabled"] = value;
            }
        }
        
        /// <summary>
        /// Hostname or IP address of the primary target
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Hostname or IP address of the primary target")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string primaryTarget {
            get {
                return ((string)(this["primaryTarget"]));
            }
            set {
                this["primaryTarget"] = value;
            }
        }
        
        /// <summary>
        /// Low threshold for response time
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Low threshold for response time")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int thresholdLow {
            get {
                return ((int)(this["thresholdLow"]));
            }
            set {
                this["thresholdLow"] = value;
            }
        }
        
        /// <summary>
        /// High threshold for response time
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("High threshold for response time")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int thresholdHigh {
            get {
                return ((int)(this["thresholdHigh"]));
            }
            set {
                this["thresholdHigh"] = value;
            }
        }
        
        /// <summary>
        /// Was the ping enabled for the secondary target
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Was the ping enabled for the secondary target")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool secondaryTargetEnabled {
            get {
                return ((bool)(this["secondaryTargetEnabled"]));
            }
            set {
                this["secondaryTargetEnabled"] = value;
            }
        }
        
        /// <summary>
        /// Hostname or IP address of the secondary target
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Hostname or IP address of the secondary target")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string secondaryTarget {
            get {
                return ((string)(this["secondaryTarget"]));
            }
            set {
                this["secondaryTarget"] = value;
            }
        }
        
        /// <summary>
        /// What reachability check is used, if true, then best of two is used, otherwise worst of two.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("What reachability check is used, if true, then best of two is used, otherwise wor" +
            "st of two.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReachabilityCheckBestOfTwo {
            get {
                return ((bool)(this["ReachabilityCheckBestOfTwo"]));
            }
            set {
                this["ReachabilityCheckBestOfTwo"] = value;
            }
        }
        
        /// <summary>
        /// How often should the ping be sent. This value is entered in seconds.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("How often should the ping be sent. This value is entered in seconds.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int pingInterval {
            get {
                return ((int)(this["pingInterval"]));
            }
            set {
                this["pingInterval"] = value;
            }
        }
    }
}
